default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.vm_user %>
  password: <%= Rails.application.credentials.vm_pass %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: volmobitest_development

test:
  <<: *default
  database: volmobitest_test

production:
  <<: *default
  database: volmobitest_production
